import java.io.PrintWriter;

/** 
 * Provides a graphical interface for selecting a pet type.
 * 
 * <p>This class allows the user to choose between three pet types: dog, cat or fish.
 * The selection is saved to a file and then proceeds to the Name Attribute screen.</p>
 * 
 * <p>Note: the swing components were generated using the NetBeans GUI builder.
 * 
 * @author Group 55
 * @version 1.0
 */
public class ChoosePet extends javax.swing.JFrame {
    private int saveSlot;

//---------------------------------------------------------------------------------------------------------
//Constructor
    /**
     * Constructor: Creates a ChoosePet instance with the specified save slot.
     * @param slot the save slot index (index is zero-based, will be incremented internally)
     */
    public ChoosePet(int slot) {
        this.saveSlot = slot + 1;
        initComponents();
        setTitle("Perfect Pet Pals - Choose Your New Pet");
        setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        setSize(800, 800);
        setLocationRelativeTo(null);
        setResizable(false);
    }
//---------------------------------------------------------------------------------------------------------
// Swing components
    /**
     * Swing components: Initializes the UI components. Citation: Generated by NetBeans GUI Builder.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        screenHeader1 = new javax.swing.JLabel();
        screenHeader2 = new javax.swing.JLabel();
        dogButton = new javax.swing.JButton();
        catButton = new javax.swing.JButton();
        fishButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(249, 241, 229));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 800));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 800));
        jPanel1.setLayout(null);

        screenHeader1.setFont(new java.awt.Font("Kristen ITC", 0, 24));
        screenHeader1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        screenHeader1.setText("Choose Your New Pet");
        jPanel1.add(screenHeader1);
        screenHeader1.setBounds(0, 130, 800, 40);

        screenHeader2.setFont(new java.awt.Font("Kristen ITC", 1, 48));
        screenHeader2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        screenHeader2.setText("New Game");
        jPanel1.add(screenHeader2);
        screenHeader2.setBounds(0, 20, 800, 128);

        dogButton.setBackground(new java.awt.Color(249, 241, 229));
        dogButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/titleDog.png")));
        dogButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        dogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dogButtonActionPerformed(evt);
            }
        });
        jPanel1.add(dogButton);
        dogButton.setBounds(290, 220, 220, 220);

        catButton.setBackground(new java.awt.Color(249, 241, 229));
        catButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/titleCat.png")));
        catButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        catButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catButtonActionPerformed(evt);
            }
        });
        jPanel1.add(catButton);
        catButton.setBounds(170, 460, 220, 220);

        fishButton.setBackground(new java.awt.Color(249, 241, 229));
        fishButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/titleFish.png")));
        fishButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        fishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fishButtonActionPerformed(evt);
            }
        });
        jPanel1.add(fishButton);
        fishButton.setBounds(410, 460, 220, 220);

        backButton.setFont(new java.awt.Font("Comic Sans MS", 0, 14));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton);
        backButton.setBounds(17, 700, 70, 35);

        // Add the panel to the frame
        this.add(jPanel1);
    }
//---------------------------------------------------------------------------------------------------------
//Button interaction 

    /**
     * Handles the dog button click event.
     * <p>Saves the dog pet type (1) to the file, creates a new NameAttribute screen,
     * and transitions to it while disposing the current screen</p>
     * 
     * @param evt the action event triggered by clicking the dog button
     */
    private void dogButtonActionPerformed(java.awt.event.ActionEvent evt) {
        writePetTypeToFile(1, this.saveSlot);
        NameAttribute nameScreen = new NameAttribute(saveSlot,1);
        nameScreen.setLocationRelativeTo(this);
        nameScreen.setVisible(true);
        this.dispose();
    }
//-------------------------------------------------------------------------
    /**
     * Handles the cat button click event.
     * <p>Saves the cat pet type (2) to the file, creates a new NameAttribute screen,
     * and transitions to it while disposing the current screen</p>
     * 
     * @param evt the action event triggered by clicking the cat button
     */
    private void catButtonActionPerformed(java.awt.event.ActionEvent evt) {
        writePetTypeToFile(2, this.saveSlot);
        NameAttribute nameScreen = new NameAttribute(saveSlot,2);
        nameScreen.setLocationRelativeTo(this);
        nameScreen.setVisible(true);
        this.dispose();
    }
//-------------------------------------------------------------------------
    /**
     * Handles the fish button click event.
     * <p>Saves the fish pet type (3) to the file, creates a new NameAttribute screen,
     * and transitions to it while disposing the current screen</p>
     * 
     * @param evt the action event triggered by clicking the fish button
     */
    private void fishButtonActionPerformed(java.awt.event.ActionEvent evt) {
        writePetTypeToFile(3, this.saveSlot);
        NameAttribute nameScreen = new NameAttribute(saveSlot,3);
        nameScreen.setLocationRelativeTo(this);
        nameScreen.setVisible(true);
        this.dispose();
    }
//-------------------------------------------------------------------------
    /**
     * Handles the back button click event.
     * 
     * <p>Creates a new MainMenu instance, positions it relative to this window,
     * makes it visible, and disposes the current ChoosePet window</p>
     * 
     * @param evt the action event triggered by clicking the back button
     */
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {
        MainMenu menuScreen= new MainMenu();
        menuScreen.setLocationRelativeTo(ChoosePet.this);
        menuScreen.setVisible(true);
        this.dispose();
    }
//---------------------------------------------------------------------------------------------------------
//Writing chosen pet type to file
    /**
     * Writes the selected pet type to the save file.
     * 
     * <p>Updates the save file with the selected pet type at the specified line index.
     * If the file doesn't have enough lines, empty lines are added until the specified index.</p>
     * 
     * @param petType the type of pet selected (1 for dog, 2 for cat, 3 for fish)
     * @param lineIndex the line index in the save file to write the pet type
     */
    private void writePetTypeToFile(int petType, int lineIndex) {
        java.io.File file = new java.io.File("savefile.csv");
        java.util.List<String> lines = new java.util.ArrayList<>();

        try (java.util.Scanner scanner = new java.util.Scanner(file)) {
            while (scanner.hasNextLine()) {
                lines.add(scanner.nextLine());
            }
        } catch (java.io.IOException e) {
            e.printStackTrace();
            return;
        }

        while (lines.size() <= lineIndex) {
            lines.add("");
        }

        lines.set(lineIndex, String.valueOf(petType));

        try (PrintWriter writer = new PrintWriter(file)) {
            for (String line : lines) {
                writer.println(line);
            }
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
    }
//---------------------------------------------------------------------------------------------------------
// Variables declaration
/** Variables declaration. These class variables for JavaSwing components were generated by NetBeans GUI Builder*/
    private javax.swing.JButton backButton;
    private javax.swing.JButton catButton;
    private javax.swing.JButton dogButton;
    private javax.swing.JButton fishButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel screenHeader1;
    private javax.swing.JLabel screenHeader2;
}
