import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

import javax.swing.JOptionPane;

/** 
 * This screen gives users the opportunity to load an existing pet or create a new pet;
 * @author group55 
 * @version 1.0.0
 */
public class LoadCreateGame extends javax.swing.JFrame {

    /** array of boolean values saying whether or not a pet is created for that slot */
    private final boolean[] isLoadSlot = new boolean[3];

//---------------------------------------------------------------------------------------------------------
/**
 * Constructor for the class. Intializes video components and updates whether or not there are pets to be loaded.
 */
    public LoadCreateGame() {
        initComponents();
        setSlotButtonsInvisible();
        loadSaveSlotsFromCSV();
        setAlwaysOnTop(true);
    }
//---------------------------------------------------------------------------------------------------------
// Swing components
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    /**
     * Initializes visual components 
     * Citation: Code generated by NetBeans GUI Builder
     */
    private void initComponents() {
        background = new javax.swing.JPanel();
        screenHeader = new javax.swing.JLabel();
        slotButton1 = createStyledSlotButton();
        slotButton2 = createStyledSlotButton();
        slotButton3 = createStyledSlotButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perfect Pet Pals - Load/Create");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(249, 241, 229));
        setMaximumSize(new java.awt.Dimension(800, 800));
        setMinimumSize(new java.awt.Dimension(800, 800));
        setPreferredSize(new java.awt.Dimension(800, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 800));

        background.setBackground(new java.awt.Color(249, 241, 229));
        background.setLayout(null);

        screenHeader.setFont(new java.awt.Font("Kristen ITC", 1, 48)); // NOI18N
        screenHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        screenHeader.setText("Load/Create Game");
        screenHeader.setToolTipText("");
        background.add(screenHeader);
        screenHeader.setBounds(0, 50, 800, 128);

        // Slot Button 1
        slotButton1.setBounds(100, 250, 150, 300);
        slotButton1.addActionListener(e -> onSlotButtonClicked(0));
        background.add(slotButton1);

        // Slot Button 2
        slotButton2.setBounds(325, 250, 150, 300);
        slotButton2.addActionListener(e -> onSlotButtonClicked(1));
        background.add(slotButton2);

        // Slot Button 3
        slotButton3.setBounds(550, 250, 150, 300);
        slotButton3.addActionListener(e -> onSlotButtonClicked(2));
        background.add(slotButton3);

        backButton.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        backButton.setText("Back");
        backButton.setPreferredSize(new java.awt.Dimension(49, 27));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        background.add(backButton);
        backButton.setBounds(17, 700, 70, 35);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }
//---------------------------------------------------------------------------------------------------------
// interaction methods (this ones freaky)
//---------------------------------------------------------------------------------------------------------
// Button styles preset


    /** 
     * Citation: Generated by NetBeans IDE 
     */
    private javax.swing.JButton createStyledSlotButton() {
        javax.swing.JButton button = new javax.swing.JButton();
        button.setFont(new java.awt.Font("Comic Sans MS", 0, 14));
        button.setFocusPainted(false);
        button.setBorderPainted(true);
        button.setContentAreaFilled(true);
        button.setPreferredSize(new java.awt.Dimension(150, 300));
        return button;
    }
//---------------------------------------------------------------------------------------------------------
    /** 
     * Hide the slot buttons
     */
    private void setSlotButtonsInvisible() {
        slotButton1.setVisible(false);
        slotButton2.setVisible(false);
        slotButton3.setVisible(false);
    }
//---------------------------------------------------------------------------------------------------------
// Button styles preset
    /** 
     * Reads information about the pets from the CSV.
     */
    private void loadSaveSlotsFromCSV() {
        String filePath = "savefile.csv";
        try (BufferedReader br = new BufferedReader(new FileReader(filePath))) {
            String line;
            String petName = "";
            String petTypeNmae = "";
            int slot = 0;
            br.readLine(); // Skip header

            while ((line = br.readLine()) != null && slot < 3) { //Read saves
                line = line.trim();
                if (line.isEmpty()) continue;

                String[] parts = line.split(",");
                int petType = Integer.parseInt(parts[0].trim());
                /** If petType = -1, this means that there is no save */
                boolean hasSave = petType != -1; 

                /** Save the pet name and type  */
                if (hasSave){ // Button formating
                    petName = parts[2].trim();
                }
                switch(petType){
                    case 1:
                        petTypeNmae = "Dog";
                        break;
                    case 2:
                        petTypeNmae = "Cat";
                        break;
                    case 3:
                        petTypeNmae = "Fish";
                        break;
                }
                /** Update the array of boolean values if the slot has a save file */
                isLoadSlot[slot] = hasSave; 

                /** Update button text based on whether or not a save file exists */
                String buttonText = hasSave ? "<html><center>Load Your "+petTypeNmae+"<br>" + petName + "</center></html>" : "Create Game"; //detrmine what to display on each button

                /** Update each button */
                switch (slot) { 
                    case 0:
                        slotButton1.setText(buttonText);
                        slotButton1.setVisible(true);
                        break;
                    case 1:
                        slotButton2.setText(buttonText);
                        slotButton2.setVisible(true);
                        break;
                    case 2:
                        slotButton3.setText(buttonText);
                        slotButton3.setVisible(true);
                        break;
                }

                slot++; //next button
            }
        } catch (IOException | NumberFormatException | ArrayIndexOutOfBoundsException e) {
            System.out.println("Error with save file, ensure save is in in correct format");
            JOptionPane.showMessageDialog(this, "Error with save file, ensure all saves are in the correct format");
            System.exit(0);
        }
    }
//---------------------------------------------------------------------------------------------------------
// Main slot button click handler
    private void onSlotButtonClicked(int slotIndex) {
        if (isLoadSlot[slotIndex]) { // Case pet saved 
            handleLoadGame(slotIndex); // load buttton
        } else {
            handleCreateGame(slotIndex); // otherwise its a save button
        }
    }
//---------------------------------------------------------------------------------------------------------
    /** 
     * Brings user to Gameplay screen based on their loaded file
     * @param slotIndex the slot containing the game information
     */
    private void handleLoadGame(int slotIndex) {
        System.out.println("Loading game from slot " + (slotIndex + 1));
        Gameplay loadedGame = new Gameplay("savefile.csv",slotIndex+1);
        loadedGame.setLocationRelativeTo(LoadCreateGame.this);
        loadedGame.setVisible(true);
        this.dispose();
    }
//---------------------------------------------------------------------------------------------------------
    /**
     * Brings user to the new pet screen
     * @param slotIndex The slot in which the information pertaining to the pet will be saved
     */
    private void handleCreateGame(int slotIndex) {
        System.out.println("Creating new game in slot " + (slotIndex + 1));
        ChoosePet tutScreen= new ChoosePet(slotIndex);
        tutScreen.setLocationRelativeTo(LoadCreateGame.this);
        tutScreen.setVisible(true);
        this.dispose();
    }
//---------------------------------------------------------------------------------------------------------
    /** 
     * Brings user back to the main menu.
     */
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        MainMenu menuScreen= new MainMenu();
        menuScreen.setLocationRelativeTo(LoadCreateGame.this);
        menuScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed
//---------------------------------------------------------------------------------------------------------
// Variables declaration
    // Variables declaration - do not modify//GEN-BEGIN:variables
    /** Generated by NetBeans GUI Builder */
    private javax.swing.JButton backButton;
    private javax.swing.JPanel background;
    private javax.swing.JLabel screenHeader;
    private javax.swing.JButton slotButton1;
    private javax.swing.JButton slotButton2;
    private javax.swing.JButton slotButton3;
    // End of variables declaration
}
