import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.time.LocalTime;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.time.Duration;
import javax.swing.JOptionPane;

/**
 * The MainMenu class represents the main menu window for the "Perfect Pet Pals" game.
 * It provides access to playing the game, opening parental controls, the tutorial, and exiting the application.
 * 
 * @author group55
 * @version 1.0
 */
public class MainMenu extends javax.swing.JFrame {

//---------------------------------------------------------------------------------------------------------
    /**
     * Constructs a new MainMenu window.
     */ 
    public MainMenu() {
        initComponents();
    }
//---------------------------------------------------------------------------------------------------------
// Swing components
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    /**
     * Initializes all Swing components and sets up the GUI layout.
     * This method is automatically generated by NetBeans GUI builder.
     */
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        parentalControls = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        playGame = new javax.swing.JButton();
        tutorial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perfect Pet Pals - Menu");
        setMaximumSize(new java.awt.Dimension(800, 800));
        setMinimumSize(new java.awt.Dimension(800, 800));
        setPreferredSize(new java.awt.Dimension(800, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 800));

        jPanel1.setBackground(new java.awt.Color(249, 241, 229));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 800));

        title.setFont(new java.awt.Font("Kristen ITC", 1, 56)); // NOI18N
        title.setText("Perfect Pet Pals");
        title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        parentalControls.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        parentalControls.setText("Parental Controls");
        parentalControls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parentalControlsActionPerformed(evt);
            }
        });

        exit.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        playGame.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        playGame.setText("Play Game");
        playGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playGameActionPerformed(evt);
            }
        });

        tutorial.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        tutorial.setText("Tutorial");
        tutorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(title)
                        .addGap(159, 159, 159))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tutorial, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(playGame, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(parentalControls, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(258, 258, 258))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(title)
                .addGap(92, 92, 92)
                .addComponent(playGame, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tutorial, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(parentalControls, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(234, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Interaction methods

    /**
     * Opens the Tutorial screen when the tutorial button is clicked.
     * 
     * @param evt the ActionEvent triggered by clicking the Tutorial button
     */
    private void tutorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorialActionPerformed
        TutorialUI tutScreen= new TutorialUI();
        tutScreen.setLocationRelativeTo(MainMenu.this);
        tutScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tutorialActionPerformed


    /**
     * Opens the Parental Controls login screen when the button is clicked.
     * 
     * @param evt the ActionEvent triggered by clicking the Parental Controls button
     */
    private void parentalControlsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parentalControlsActionPerformed
        ParentalLoginScreenUI parentLogin = new ParentalLoginScreenUI(this);
        parentLogin.setLocationRelativeTo(MainMenu.this);
        parentLogin.setVisible(true);
    }//GEN-LAST:event_parentalControlsActionPerformed


    /**
     * Handles the Play Game button click.
     * Checks if the current time is within the allowed parental time range,
     * and if allowed, opens the game screen.
     * 
     * @param evt the ActionEvent triggered by clicking the Play Game button
     */
    private void playGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playGameActionPerformed
        String csvFile = "savefile.csv";
        String line;
        int targetRow = 4; // 5th row
        String[] rowData = null;

        try (BufferedReader br = new BufferedReader(new FileReader(csvFile))) {
            int currentRow = 0;
            while ((line = br.readLine()) != null) {
                if (currentRow == targetRow) {
                    rowData = line.split(",");
                    break;
                }
                currentRow++;
            }
        } catch (IOException e) {
            System.out.println("Error: File not found");
            return;
        }

        if (rowData != null && rowData.length >= 2) { //Exctract times
            try {
                LocalTime now = LocalTime.now();
                LocalTime startTime = LocalTime.parse(rowData[0].trim());
                LocalTime endTime = LocalTime.parse(rowData[1].trim());

                if (!ParentalControls.isRestricted() || !now.isBefore(startTime) && !now.isAfter(endTime)) { //If between times
                    LoadCreateGame game = new LoadCreateGame();
                    game.setLocationRelativeTo(MainMenu.this);
                    game.setVisible(true);
                    this.dispose();
                } else {
                JOptionPane.showMessageDialog(this, "The game is not available right now. Please come back later.");
                }
            } catch (DateTimeParseException e) {
                System.out.println("Error: File not found");
            }
        } else {
            System.out.println("Error: File not found");
        }
    }//GEN-LAST:event_playGameActionPerformed

    /**
     * Reads from the save file and updates playtime statistics before exiting.
     */
    private void readAndPrint(){
        String hold = "";
        ArrayList<String> lines = new ArrayList<String>();
        try {
            // ArrayList<String> controls = new ArrayList<String>();
            File saveFile = new File("savefile.csv");
            BufferedReader fileReader = new BufferedReader(new FileReader(saveFile));
            LocalTime start;
            // LocalTime diff;
            Duration diff;
            String currLine;
            int sessions;
            for (int i = 0; i < 4; i++) {
                if ((currLine = fileReader.readLine()) != null){
                    lines.add(currLine);
                }
            }
            String [] vals = fileReader.readLine().split(",");
            fileReader.close();
            start = LocalTime.parse(vals[4]);
            diff = Duration.between(start,LocalTime.now());
            vals[2] = String.valueOf(Integer.parseInt(vals[2])+diff.toMinutes());
            sessions = Integer.parseInt(vals[3]);
            vals[3] = String.valueOf(sessions+1);
            for (int i = 0; i < vals.length; i++){
                hold = hold + vals[i];
                if (i != vals.length-1) hold = hold + ",";
            }
            PrintWriter fileWriter = new PrintWriter(new FileWriter("savefile.csv", false));
            for (int i = 0; i < 4; i++) {
                System.out.println(lines.get(i));
                fileWriter.println(lines.get(i));
            }
            fileWriter.println(hold);
            fileWriter.close();

        }   
        catch (IOException e){
            System.out.println("error");
        }
        
    }


    /**
     * Handles the Exit button click.
     * Saves updated playtime stats and exits the program.
     * 
     * @param evt the ActionEvent triggered by clicking the Exit button
     */
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        readAndPrint();
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton parentalControls;
    private javax.swing.JButton playGame;
    private javax.swing.JLabel title;
    private javax.swing.JButton tutorial;
    // End of variables declaration//GEN-END:variables
}
