import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import javax.swing.JOptionPane;


/** 
 * Within the create a pet process, brings a user to a screen where they can name their pet and see attributes.
 * @author group55
 * @version 1.0
 */
public class NameAttribute extends javax.swing.JFrame {

    /** the saveSlot that the pet will be saved at - related to the line in the file */
    private int saveSlot;
    /** the type of pet being saved */
    private int petType;

//---------------------------------------------------------------------------------------------------------
//Constructor 
    /**
     * Initalizes the visual components for this screen
     * @param slot the slot where the information will be saved
     * @param petType the type of pet to be displayed
     */
    public NameAttribute(int slot, int petType) {
        this.saveSlot = slot;
        this.petType = petType;
        initComponents();
        getContentPane().setBackground(Color.white);
        updateAttributeLabels(); 
    }  
//---------------------------------------------------------------------------------------------------------
// Swing components
    @SuppressWarnings("unchecked")
    /**
     * Initializes visual components
     * Generated by NetBeans GUI builder
     */
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
    
        // ✅ Add the image label
        petImageLabel = new javax.swing.JLabel();
    
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setTitle("Perfect Pet Pals - Name Your Pet!");
        setPreferredSize(new java.awt.Dimension(800, 800));
    
        jPanel2.setBackground(new java.awt.Color(249, 241, 229));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 800));
        jPanel2.setLayout(null);
    
        petImageLabel.setBounds(30, 250, 200, 200); // You can tweak this
        jPanel2.add(petImageLabel);
    
        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 48)); // NOI18N
        jLabel1.setText("New Game");
        jLabel1.setBounds(250, 30, 400, 50);
        jPanel2.add(jLabel1);
    
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Awesome! You selected the pet:");
        jLabel2.setBounds(250, 90, 500, 40);
        jPanel2.add(jLabel2);
    
        jLabel3.setFont(new java.awt.Font("Kristen ITC", 1, 36)); // NOI18N
        jLabel3.setText("Name your pet:");
        jLabel3.setBounds(250, 150, 300, 40);
        jPanel2.add(jLabel3);
    
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(102, 102, 102));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBounds(550, 150, 200, 50);
        jPanel2.add(jTextField1);
    
        jLabel4.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jLabel4.setText("Starting Attributes");
        jLabel4.setBounds(250, 250, 300, 30);
        jPanel2.add(jLabel4);
    
        jLabel5.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        jLabel5.setText("Health:");
        jLabel5.setBounds(250, 300, 500, 30);
        jPanel2.add(jLabel5);
    
        jLabel6.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        jLabel6.setText("Sleep:");
        jLabel6.setBounds(250, 340, 500, 30);
        jPanel2.add(jLabel6);
    
        jLabel7.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        jLabel7.setText("Happiness:");
        jLabel7.setBounds(250, 380, 500, 30);
        jPanel2.add(jLabel7);
    
        jLabel8.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        jLabel8.setText("Fullness:");
        jLabel8.setBounds(250, 420, 500, 30);
        jPanel2.add(jLabel8);
    
        jButton1.setFont(new java.awt.Font("Kristen ITC", 1, 48)); // NOI18N
        jButton1.setText("Click to Start Game!");
        jButton1.setBounds(100, 650, 600, 85);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
    
        getContentPane().setLayout(null);
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 800, 800);
    
        pack();
        setLocationRelativeTo(null);
    }
    
//---------------------------------------------------------------------------------------------------------
    /**
     * Method to update the CSV row for the given save slot
     * @param petName The user's chosen name for the pet.
     *  */ 
    private void updateGameData(String petName) {
        String filePath = "savefile.csv";
        File file = new File(filePath);
        List<String> lines = new ArrayList<>();
        /** Read each line from the csv file */
        try (Scanner scanner = new Scanner(file)) {
            while (scanner.hasNextLine()) {
                lines.add(scanner.nextLine());
            }
        } catch (IOException e) {
            e.printStackTrace();
            return;
        }
        /** Retrieve the pet type stored in the save file */
        String oldLine = lines.get(saveSlot);
        String petType = "";
        if (oldLine != null && !oldLine.trim().isEmpty()) {
            String[] parts = oldLine.split(",");
            if (parts.length > 0) {
                petType = parts[0].trim();
            }
        }
        String health = "100";
        switch (petType) {
            /** Dog */
            case "1": 
            health = "150";
                break;
            /**  Cat */
            case "2": 
            health = "100";
                break;
                /** Fish */
            case "3": 
            health = "75";
                break;
        } 
        /** build the new row in the correct file format, with initial values */
        String newRow = petType + "," + "5" + "," + petName + "," + health + ",100,100,100,0,10,5,1,10,5,1";
        lines.set(saveSlot, newRow);

        /** Write the updated lines back to the file */
        try (PrintWriter writer = new PrintWriter(file)) {
            for (String line : lines) {
                writer.println(line);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
//---------------------------------------------------------------------------------------------------------
    /** 
     * Updates the attributes on the screen based on the type of pet
     */
    private void updateAttributeLabels() {
        switch (petType) {
            /** Show attributes of the pet based on pet type (different starting healths and rates of decline) */
            case 1: // DOG
                jLabel5.setText("Health: 150");
                jLabel6.setText("Sleep: Increases Normally");
                jLabel7.setText("Happiness: Gains More Happiness");
                jLabel8.setText("Fullness: Decreases Faster");
                break;

            case 2: // CAT
                jLabel5.setText("Health: 100");
                jLabel6.setText("Sleep: Gains More Sleep");
                jLabel7.setText("Happiness: Decreases Faster");
                jLabel8.setText("Fullness: Decreases Normally");
                break;

            case 3: // FISH
                jLabel5.setText("Health: 75");
                jLabel6.setText("Sleep: Decreases More");
                jLabel7.setText("Happiness: Decreases Normally");
                jLabel8.setText("Fullness: Gains More Fullness");
                break;

            default:
                jLabel5.setText("Health: Unknown");
                jLabel6.setText("Sleep: Unknown");
                jLabel7.setText("Happiness: Unknown");
                jLabel8.setText("Fullness: Unknown");
                break;
        }
        String imagePath = "";
        /** Image to be shown on the screen */
        switch (petType) {
            case 1: // DOG
                imagePath = "/img/titleDog.png";
                break;
            case 2: // CAT
                imagePath = "/img/titleCat.png";
                break;
            case 3: // FISH
                imagePath = "/img/titleFish.png";
                break;
        }

if (!imagePath.isEmpty()) {
    petImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource(imagePath)));
}

    }
//---------------------------------------------------------------------------------------------------------
// Interaction methods
    /**
     * Action handler for the "Click to Start Game!" button
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        String petName = jTextField1.getText().trim();
        /** Ask user to enter name if not there */
        if (petName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a name for your pet.");
            return;
        }
        /** Write to file */
        updateGameData(petName);
        /** Open Gameplay screen */
        Gameplay loadedGame = new Gameplay("savefile.csv",saveSlot);
        loadedGame.setLocationRelativeTo(NameAttribute.this);
        loadedGame.setVisible(true);
        this.dispose();
    }

    // Variables declaration - do not modify   
    /** Generated by Netbeans GUI Builder */                  
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel petImageLabel;
    // End of variables declaration                   
}
