import java.util.Arrays;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * The ParentalLoginScreenUI class creates a login screen for accessing parental controls.
 * It provides a simple GUI where a user can enter a 4-digit PIN to unlock access to the parental control features.
 * If the PIN is correct, the parental control menu is shown; otherwise, an error dialog is displayed.
 * 
 * @author group55
 * @version 1.0
 */
public class ParentalLoginScreenUI extends javax.swing.JFrame {

//Constructor 
    public ParentalLoginScreenUI(JFrame menuFrame) {
        initComponents(menuFrame);
    }


    // Swing components
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents

    /**
     * Constructs the Parental Login screen and initializes all Swing components and sets up the GUI layout.
     * This method is automatically generated by NetBeans GUI builder.
     */
    private void initComponents(JFrame menuFrame) {

        jPanel1 = new javax.swing.JPanel();
        jPasswordField1 = new javax.swing.JPasswordField();
        backButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        enterPassword = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setMaximumSize(new java.awt.Dimension(800, 215));
        setMinimumSize(new java.awt.Dimension(800, 215));

        jPanel1.setBackground(new java.awt.Color(249, 241, 229));

        jPasswordField1.setText(null);
        jPasswordField1.setPreferredSize(new java.awt.Dimension(90, 27));

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButton.doClick(); // Simulate a click on the login button
            }
        });

        backButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        loginButton.setBackground(new java.awt.Color(189, 219, 250));
        loginButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt, menuFrame);
            }
        });

        title.setFont(new java.awt.Font("Kristen ITC", 1, 40)); // NOI18N
        title.setText("Parental Controls");

        enterPassword.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        enterPassword.setText("Enter PIN:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(enterPassword)
                        .addGap(18, 18, 18)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(205, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title)
                .addGap(245, 245, 245))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


// interaction methods

    /**
     * Action triggered when the "Back" button is clicked.
     * This closes the login screen and returns to the previous screen.
     * 
     * @param evt the action event from the button
     */
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed


    /**
     * Action triggered when the "Login" button is clicked or the user presses Enter.
     * Compares the entered password to the hardcoded PIN (2212) and either opens the parental control menu
     * or shows an error message if the PIN is incorrect.
     * 
     * @param evt the action event from the button
     * @param menuFrame the main menu frame to close upon successful login
     */
    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt, JFrame menuFrame) {//GEN-FIRST:event_loginButtonActionPerformed
        char[] correctPassword = {'2', '2', '1', '2'};
        char[] currPassword = jPasswordField1.getPassword();
        if (Arrays.equals(currPassword, correctPassword)) {
            ParentalControls parentScreen= new ParentalControls();
            parentScreen.setLocationRelativeTo(ParentalLoginScreenUI.this);
            parentScreen.setVisible(true);
            this.dispose();
            menuFrame.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Pin incorrect, please try again!");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_loginButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel enterPassword;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
