import javax.swing.JOptionPane;

/** 
 * Provides a graphical interface for the game pause screen.
 * 
 * <p>This class creates a small screen that appears when the game is paused, allowing 
 * the player to either return to the game or save and quit to the main menu.</p>
 * 
 * <p>Note: the swing components were generated using the NetBeans GUI builder.
 * 
 * @author Group 55
 * @version 1.0
 */

public class PasueScreenUI extends javax.swing.JFrame {
    private Gameplay parentGame;

//---------------------------------------------------------------------------------------------------------
//Constructor
    /**
     * Constructor: Creates a PasueScreenUI instance which is linked to the parent game
     * 
     * @param parent the parent Gameplay instance that created this pause screen
     */
    public PasueScreenUI(Gameplay parent) {
        initComponents();
        this.parentGame = parent;
    }

//---------------------------------------------------------------------------------------------------------
// Swing components
    /**
     * Swing components: Initializes the UI components. Generated by NetBeans GUI Builder
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        borderPanel = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        titleLable = new javax.swing.JLabel();
        saveQuitButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Perfect Pet Pals - Pause");
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(400, 200));
        setMinimumSize(new java.awt.Dimension(400, 200));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(400, 200));

        borderPanel.setBackground(new java.awt.Color(0, 0, 0));
        borderPanel.setMaximumSize(new java.awt.Dimension(400, 200));
        borderPanel.setMinimumSize(new java.awt.Dimension(400, 200));
        borderPanel.setPreferredSize(new java.awt.Dimension(400, 200));

        mainPanel.setBackground(new java.awt.Color(249, 241, 229));
        mainPanel.setPreferredSize(new java.awt.Dimension(380, 180));
        mainPanel.setVerifyInputWhenFocusTarget(false);

        titleLable.setFont(new java.awt.Font("Kristen ITC", 1, 48)); // NOI18N
        titleLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLable.setText("Game Paused");

        saveQuitButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        saveQuitButton.setText("Save and Quit");
        saveQuitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveQuitButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        backButton.setText("Back to Game");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titleLable, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveQuitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(titleLable, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveQuitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout borderPanelLayout = new javax.swing.GroupLayout(borderPanel);
        borderPanel.setLayout(borderPanelLayout);
        borderPanelLayout.setHorizontalGroup(
            borderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        borderPanelLayout.setVerticalGroup(
            borderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(borderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(borderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//---------------------------------------------------------------------------------------------------------
// interaction methods
    /**
     * Handles the back button click event
     * 
     * <p>Resumes the parent game, resumes the game music, and disposes this pause screen.</p>
     * 
     * @param evt the action event triggered by clicking the back button
     */
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        parentGame.resumeGame();
        MusicPlayer.resumeMusic();
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed
//-------------------------------------------------------------------------
    /**
     * Handles the save and quit button click event
     * 
     * <p>Captures the current inventory amounts from the game, updates the pet's inventory data, writes the state to file,
     * displays a goodbye message, returns to the main menu, stops the music.</p>
     * 
     * @param evt the action event triggered by clicking the save and quit button
     */
    private void saveQuitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveQuitButtonActionPerformed
        int[] inventoryAmounts = new int[6];
        for (int i = 0; i < 6; i++) {
            inventoryAmounts[i] = parentGame.inventory[i].getAmmount();
        }
        parentGame.p.setInventoryAmounts(inventoryAmounts);
        Pet.writeToFile("savefile.csv", parentGame.lineNum, parentGame.p);
        JOptionPane.showMessageDialog(this, "Game saved! \n"+parentGame.p.getName()+" hopes to see you soon!");
        MainMenu menuScreen= new MainMenu();
        MusicPlayer.stopMusic();
        menuScreen.setLocationRelativeTo(PasueScreenUI.this);
        menuScreen.setVisible(true);
        parentGame.dispose();
        this.dispose();
    }//GEN-LAST:event_saveQuitButtonActionPerformed
//---------------------------------------------------------------------------------------------------------
// Variables declaration
    /** Variables declaration. These class variables for JavaSwing components were generated by NetBeans GUI Builder*/
    private javax.swing.JButton backButton;
    private javax.swing.JPanel borderPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton saveQuitButton;
    private javax.swing.JLabel titleLable;
    // End of variables declaration//GEN-END:variables
}
