import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;

import java.time.LocalTime;
import java.util.ArrayList;
/** GUI component */
import javax.swing.JOptionPane;
/**
 * TitleScreenUI Objects open a title screen, this class contains the main method for the project
 * <br><br>
 *
 * <b>Example Use:</b>
 * <pre>
 * {@code 
 *      TitleScreenUI t = new TitleScreenUI();
 *      t.setVisible(true);
 * }
 * </pre>
 * 
 * <b>Example Output:</b>A Title scrren for the game <br>
 * 
 * @version 1.0.0
 * @author Group 55
 */
public class TitleScreenUI extends javax.swing.JFrame {
    /**
     * Write a game start to file, used in parental controls
     * 
     */
    private void writeStart() {
        /** first, read and save the existing information */
        String currLine;
        ArrayList<String> lines = new ArrayList<String>();
        File saveFile = new File("savefile.csv");
        String start = "00:01:00";
        String parentalControls = "";
        String [] vals = {};
       
        try {
            /**  read up until the parental controls line */
            BufferedReader fileReader = new BufferedReader(new FileReader(saveFile));
            for (int i = 0; i < 4; i++) {
                if ((currLine = fileReader.readLine()) != null){
                    lines.add(currLine);
                }
            }
            vals = fileReader.readLine().split(",");
            vals[4] = LocalTime.now().toString();
            fileReader.close();
            /** Error handeling given bad file input */
        } catch (NullPointerException | IOException  | ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Error with save file, ensure exists and all lines are in the correct format, See README for file requierments");
            System.exit(0);
        }
        try {    
            /** Write load time to file */
            PrintWriter fileWriter = new PrintWriter(new FileWriter("savefile.csv", false));
            if (vals.length != 6){
                System.out.println("Error: Could not get current time.");
            } else {
                for (int j = 0; j < vals.length; j++){
                    parentalControls = parentalControls+vals[j];
                    if (j != vals.length-1){
                        parentalControls = parentalControls + ",";
                    }
                }
            }
            for (int i = 0; i < 4; i++) {
                fileWriter.println(lines.get(i));
            }
            fileWriter.println(parentalControls);
            fileWriter.close();
            
        }
        /** Error handeling given bad file input */
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error with save file, ensure exists and all lines are in the correct format, See README for file requierments");
            System.exit(0);
        }

    }
    /**
     * TitleScrrenUI constructor. Creates a new TitleScrrenUI object.
     * 
     * @see writeStart
     */
    public TitleScreenUI() {
        initComponents();
        writeStart();
    }
    /**
     * Java swing components generated by NetBeans GUI builder
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        doghouseImg = new javax.swing.JLabel();
        catImg = new javax.swing.JLabel();
        fishImg = new javax.swing.JLabel();
        dogImg = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setTitle("Perfect Pet Pals - Title");
        setMinimumSize(new java.awt.Dimension(800, 800));

        mainPanel.setBackground(new java.awt.Color(249, 241, 229));
        mainPanel.setMaximumSize(new java.awt.Dimension(800, 800));
        mainPanel.setMinimumSize(new java.awt.Dimension(800, 800));
        mainPanel.setName(""); // NOI18N
        mainPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainPanelMouseClicked(evt);
            }
        });

        title.setFont(new java.awt.Font("Kristen ITC", 1, 68)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Perfect Pet Pals");

        doghouseImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PPPhouse.png"))); // NOI18N

        catImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/titleCat.png"))); // NOI18N

        fishImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/titleFish.png"))); // NOI18N

        dogImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/titleDog.png"))); // NOI18N

        title1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title1.setText("<html><div style='font-size:16px; text-align:center;'>By: Karim, Evan, Madhav, Feras, Sterling<br/>Group 55, CS2212 Winter 2025<br/>Click Anywhere to Play!</div></html>");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(doghouseImg))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(dogImg)
                        .addGap(18, 18, 18)
                        .addComponent(catImg)
                        .addGap(18, 18, 18)
                        .addComponent(fishImg)))
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(title1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(doghouseImg)
                .addGap(47, 47, 47)
                .addComponent(title)
                .addGap(73, 73, 73)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fishImg)
                    .addComponent(dogImg)
                    .addComponent(catImg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(title1)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Click anywhere for starting game
     * 
     * @param e event clicked
     * @see MainMenu.java
     */
    private void mainPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainPanelMouseClicked
        /** Load Main menu */
        MainMenu menuScreen= new MainMenu();
        menuScreen.setLocationRelativeTo(TitleScreenUI.this);
        menuScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mainPanelMouseClicked
    /**
     * Main method, entry point for game
     * Generated by netBeans GUI builder
     */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TitleScreenUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TitleScreenUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TitleScreenUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TitleScreenUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TitleScreenUI().setVisible(true);
            }
        });
    }
    /**
     * SWing elements variables, generated by netBeans GUI builder
     */
    // Variables declaration
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel catImg;
    private javax.swing.JLabel dogImg;
    private javax.swing.JLabel doghouseImg;
    private javax.swing.JLabel fishImg;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    // End of variables declaration//GEN-END:variables
}
