/**
 * Provides a graphical interface for this game's tutorial information.
 * 
 * <p>Note: This code was almost entirely generated using the NetBeans GUI builder.
 * Only the textBox.setText() content for each textBox and image directories were manually added after generation.</p>
 * 
 * @author Group 55
 * @version 1.0
 */

public class TutorialUI extends javax.swing.JFrame {

    //---------------------------------------------------------------------------------------------------------
    //Constructor
    /** 
     * Constructor: Creates a TutorialUI instance. Generated by NetBeans GUI Builder.
    */
        public TutorialUI() {
            initComponents();
        }
    
    //---------------------------------------------------------------------------------------------------------
    // Swing components
    /**
     * Swing components: Initializes the UI components. Majority generated by NetBeans GUI Builder.
     */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {
    
            mainPanel = new javax.swing.JPanel();
            title = new javax.swing.JLabel();
            backButton = new javax.swing.JButton();
            img1 = new javax.swing.JLabel();
            img2 = new javax.swing.JLabel();
            img3 = new javax.swing.JLabel();
            img4 = new javax.swing.JLabel();
            textBox1 = new javax.swing.JTextArea();
            textBox2 = new javax.swing.JTextArea();
            textBox3 = new javax.swing.JTextArea();
            textBox4 = new javax.swing.JTextArea();
    
            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setResizable(false);
            setTitle("Perfect Pet Pals - Tutorial");
            setBackground(new java.awt.Color(204, 0, 153));
            setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            mainPanel.setBackground(new java.awt.Color(249, 241, 229));
            mainPanel.setMaximumSize(new java.awt.Dimension(850, 850));
            mainPanel.setMinimumSize(new java.awt.Dimension(850, 850));
            mainPanel.setPreferredSize(new java.awt.Dimension(850, 850));
            mainPanel.setName(""); // NOI18N
    
            title.setFont(new java.awt.Font("Kristen ITC", 1, 48)); // NOI18N
            title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            title.setText("Tutorial");
    
            backButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
            backButton.setText("Back");
            backButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    backButtonActionPerformed(evt);
                }
            });
    
            /**Image directories manually added */
            img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/namePet.png"))); // NOI18N
    
            img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/petStats.png"))); // NOI18N
    
            img3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/playPet.png"))); // NOI18N
    
            img4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/scoreImg.png"))); // NOI18N
    
            /** The content for the following four text boxes were manually added */
            textBox1.setEditable(false);
            textBox1.setBackground(new java.awt.Color(255, 255, 255));
            textBox1.setLineWrap(true);
            textBox1.setColumns(24);
            textBox1.setFont(new java.awt.Font("Comic Sans MS", 0, 16));;
            textBox1.setText("Welcome to Perfect Pet Pals! \nStart by picking your pet pal: \n  - A cat, dog or fish!\nThen, give your pet a name!");
    
            textBox2.setEditable(false);
            textBox2.setBackground(new java.awt.Color(255, 255, 255));
            textBox2.setLineWrap(true);
            textBox2.setColumns(24);
            textBox2.setRows(4);
            textBox2.setFont(new java.awt.Font("Comic Sans MS", 0, 16));;
            textBox2.setText("Track Your Pet's Needs!\r\n" + //
                            "Health: Is your pet feeling good?\r\n" + //
                            "Sleep: Is your pet nice and rested?\r\n" + //
                            "Happiness: Is your pet having fun?\r\n" + //
                            "Fullness: Is your pet's tummy full?");
    
            textBox3.setEditable(false);
            textBox3.setBackground(new java.awt.Color(255, 255, 255));
            textBox3.setLineWrap(true);
            textBox3.setColumns(24);
            textBox3.setRows(4);
            textBox3.setFont(new java.awt.Font("Comic Sans MS", 0, 16));;
            textBox3.setText("Gameplay Controls!\r\n" + //
                            "Play (P): Fun time! (^Happiness)\r\n" + //
                            "Feed (F): Meal time! (^Fullness)\r\n" + //
                            "Gift (G): Special treats! (^Happiness)\r\n" + //
                            "Exercise (E): Get moving! (^Health)\r\n" + //
                            "Bed (B): Rest time! (^Sleepiness)\r\n" + //
                            "Vet (V): Feel better! (^Health)\r\n" + //
                            "Inventory (I): Check your items\r\n" + //
                            "Pause (ESC): Take a break/save + quit!\r\n" + //
                            "Music (M): Turn sound on/off!");
    
            textBox4.setEditable(false);
            textBox4.setBackground(new java.awt.Color(255, 255, 255));
            textBox4.setLineWrap(true);
            textBox4.setColumns(24);
            textBox4.setRows(4);
            textBox4.setFont(new java.awt.Font("Comic Sans MS", 0, 16));;
            textBox4.setText("Earn a high score!\r\n" +
                            "Keep your pet happy and healthy :)\r\n" + 
                            "The better you care for your pet, the more points you'll rack up!");
    
            javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
            mainPanel.setLayout(mainPanelLayout);
            mainPanelLayout.setHorizontalGroup(
                mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(backButton)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                    .addContainerGap(251, Short.MAX_VALUE)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(249, 249, 249))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                    .addGap(54, 54, 54)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(textBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(img4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(img2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(img1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(img3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(39, 39, 39))
            );
            mainPanelLayout.setVerticalGroup(
                mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(title)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(img1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(textBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(img2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textBox2))
                    .addGap(15, 15, 15)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(img3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textBox3))
                    .addGap(15, 15, 15)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(img4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textBox4))
                    .addGap(5, 5, 5)
                    .addComponent(backButton)
                    .addContainerGap())
            );
    
            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
    
            pack();
        }// </editor-fold>//GEN-END:initComponents
    //---------------------------------------------------------------------------------------------------------
    // interaction methods

    /**
     * Handles the back button click event.
     * 
     * Creates a new MainMenu instance, positions it relative to this window, makes it visible, and disposes the current TutorialUI window
     * 
     * @param evt the action event triggered by clicking the back button
     */
        private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
            MainMenu menuScreen= new MainMenu();
            menuScreen.setLocationRelativeTo(TutorialUI.this);
            menuScreen.setVisible(true);
            this.dispose();
        }//GEN-LAST:event_backButtonActionPerformed
    //---------------------------------------------------------------------------------------------------------
    // Variables declaration
        // Variables declaration - do not modify//GEN-BEGIN:variables

        /** Variables declaration. These class variables for JavaSwing components were generated by NetBeans GUI Builder*/
        private javax.swing.JButton backButton;
        private javax.swing.JLabel img1;
        private javax.swing.JLabel img2;
        private javax.swing.JLabel img3;
        private javax.swing.JLabel img4;
        private javax.swing.JPanel mainPanel;
        private javax.swing.JTextArea textBox1;
        private javax.swing.JTextArea textBox2;
        private javax.swing.JTextArea textBox3;
        private javax.swing.JTextArea textBox4;
        private javax.swing.JLabel title;
        // End of variables declaration//GEN-END:variables
    }
    
    